stages:
  - test
  - build

test:
  stage: test
  image: node:20.6
  script:
    - npm install
    - echo "Running extremely simple test"
    - npm run test
    - echo "Test passed successfully!"

build:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  script:
    # Use GitLab's predefined CI/CD variables
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  # Tell GitLab this job needs access to the Docker socket
  tags:
    - docker