stages:
  - test
  - build

test:
  stage: test
  image: node:20.6
  script:
    - npm install
    - echo "Running extremely simple test"
    - npm run test
    - echo "Test passed successfully!"
  only:
    - main

build:
  stage: build
  image: node:latest
  script:
    - npm install
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
