name: Backend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.6"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          echo "Running backend tests..."
          npm run test
          echo "✅ Backend tests passed!"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        id: repo
        run: echo "repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.repository }}:latest
            ghcr.io/${{ steps.repo.outputs.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  trigger_orchestrator:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Convert repository name to lowercase
        id: repo
        run: echo "repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Trigger orchestrator deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository: YOUR_ORG/orchestrator-repo
          event-type: backend-updated
          client-payload: |
            {
              "service": "backend",
              "image": "ghcr.io/${{ steps.repo.outputs.repository }}:latest",
              "sha": "${{ github.sha }}",
              "ref": "${{ github.ref }}"
            }
